### ISSUE TITLE
cant find the .env file

### ISSUE THREAD

**Issue by ozhenn** [redaxmedia/twitter-drone#1]
can u help please?

**Comment by redaxmedia** [comment]
Hello,

Please create your own `.env` file - I did not commit the file because it is not recommended.

[Should I commit my .env file?](https://www.npmjs.com/package/dotenv#should-i-commit-my-env-file)

> No. We strongly recommend against committing your .env file to version control. It should only include environment-specific values such as database passwords or API keys. Your production database should have a different password than your development database.
